// <auto-generated />
using System;
using KhoraControl.Setup.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KhoraControl.Migrations
{
    [DbContext(typeof(KhoraContext))]
    [Migration("20240801182316_CadastroVeiculos")]
    partial class CadastroVeiculos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("KhoraControl.Model.Veiculo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ano")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDaCompra")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataProximaRevisao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataUltimaRevisao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ID_Concessionaria")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KmProximaRevisao")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KmQuandoComprado")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KmRodados")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KmUltimaRevisao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalSalvamentoDeDados")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Motorista")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SugestaoConcessionaria")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
